openapi: 3.0.3
info:
  title: Reporting API
  version: "1.0"
  description: |-
    Get direct access to your impact totals, which refresh every 10 minutes. Requests to the reporting API do not require authorisation.

    Click on an item from the menu on the left to explore the available endpoints.
servers:
  - url: "https://public.ecologi.com"
    description: Production
paths:
  "/users/{username}/trees":
    parameters:
      - $ref: "#/components/parameters/username"
    get:
      summary: Get Total Number of Trees
      operationId: get-user-trees
      description: The total number of trees this user has funded. Data refreshes every 10 minutes.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                description: ""
                type: object
                properties:
                  total:
                    type: number
                    description: All paid trees for this user
                    example: 16348
                  pending:
                    type: number
                    description: All unpaid trees for this user
                    example: 871
  "/users/{username}/carbon-offset":
    parameters:
      - $ref: "#/components/parameters/username"
    get:
      summary: Get Total Tonnes of CO2e avoided
      operationId: get-user-carbon-offset
      description: The total number of tonnes of emissions this user has avoided. Data refreshes every 10 minutes.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                description: ""
                type: object
                properties:
                  total:
                    type: number
                    description: All paid carbon avoidance for this user
                    example: 187.4
                  pending:
                    type: number
                    description: All unpaid carbon avoidance for this user
                    example: 14.9
  "/users/{username}/impact":
    parameters:
      - $ref: "#/components/parameters/username"
    get:
      summary: Get Total Impact
      operationId: get-user-impact
      description: "A combination of how many trees this user has funded and how many tonnes of emissions have been avoided, in a single request. Data refreshes every 10 minutes."
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                description: ""
                type: object
                properties:
                  trees:
                    type: number
                    description: All paid trees for this user
                    example: 16348
                  carbonOffset:
                    type: number
                    description: All paid carbon avoidance for this user
                    example: 187.4
                  pending:
                    type: object
                    description: All unpaid impact for this user
                    properties:
                      trees:
                        type: number
                        example: 871
                      carbonOffset:
                        type: number
                        example: 14.9
components:
  parameters:
    username:
      name: username
      in: path
      required: true
      schema:
        type: string
        example: business-name
      description: Your Ecologi username
  schemas: {}
